### ISSUE TITLE
Use nodemon to auto restart server on changes

### ISSUE THREAD

**Issue by milkisevil** [milkisevil/spotidrop#6]
I only found out about this today... how have I gotten by for so long without it?!?!?
http://nodemon.io

**Comment by ianmcgregor** [comment]
`forever --watch` also does this. Not sure which is best.

**Comment by ianmcgregor** [comment]
Just looked into it a bit and could be good to use both like:

```shell
NODE_ENV=dev NO_AUTH=true forever -c nodemon index.js --exitcrash
```

**Comment by milkisevil** [comment]
@ianmcgregor  I've implemented `nodemon` only for now, going to close, but feel free to reopen/create another ticket if you'd still like to use `forever` too.
