### ISSUE TITLE
Define API for v1

### ISSUE THREAD

**Issue by ianmcgregor** [milkisevil/spotidrop#7]
This is a list of what we currently have in terms of api endpoints. Need to figure out if there's anything missing and what to use rest/websocket for.

# rest

## playlist

- [x] /api/playlists (get)  
- [x] /api/playlists/:playlist_id (get, put, delete)
- [ ] :-1: /api/playlists/:playlist_id/play (get)
- [x] /api/playlists/:playlist_id/tracks (get, post)
- [ ] /api/playlists/:playlist_id/tracks/:track_id/upvote

## track

This call could be made internally whenever a track is added and the artwork data stored in the track model. Do we even need an api endpoint for 'track'?

- [ ] /api/track/:track_id/artwork

## search

Search might be better off coming through the socket (from and to the individual client) as we'll probably have a 'results update as you type' thing going on and it will be faster. Prob harder to code like that though.

- [ ] /api/search/:terms (get)

## users

The 'me' route could probably be merged into users as users/me. We could log user actions so we can have some nice stats later.

- [ ] /api/me (get)
- [ ] /api/users (get)

## auth

- [ ] /auth/twitter?redirect={url} (get)
- [ ] /auth/google?redirect={url} (get)
- [ ] /auth/facebook?redirect={url} (get)
- [ ] /auth/spotify?redirect={url} (get)

# websocket

## client to server

- [ ] 'client:connect', (userId)
- [ ] 'client:pause'
- [ ] 'client:resume'

## server to all clients

- [ ] 'track:start', (track)
- [ ] 'track:progress', (progress)
- [ ] 'user:connect', (connectedUsers)
- [ ] 'pause'
- [ ] 'resume'
- [ ] 'track:upvote', (data)
- [ ] 'playlist:end'

**Comment by milkisevil** [comment]
Did you manage to take a look at https://github.com/milkisevil/spotidrop/wiki/API-Overview — just want to make sure we're not duplicating effort. I guess this issue is more about what exists, and the wiki page is about what could exist... probably need to merge somehow?

**Comment by ianmcgregor** [comment]
Yep :+1: Thought an issue could be a good way to briefly list what we actually have, discuss it, make a few decisions and track what's implemented.

**Comment by ianmcgregor** [comment]
Have updated the wiki page with the latest
